#!/usr/bin/env python3
"""Generate deterministic fake error-diagnostics test cases for Zig stdlib error diagnostics lab."""
import json, random

random.seed(42)

cases = []

def add(case_id, category, **kw):
    c = {
        "case_id": case_id,
        "category": category,
        "fake_record_name": kw.get("fake_record_name", f"fake_{case_id}"),
        "synthetic_input": kw.get("synthetic_input", f"fake_input_{case_id}"),
        "synthetic_token_label": kw.get("synthetic_token_label", "demo_token"),
        "expected_error_label": kw.get("expected_error_label", "None"),
        "expected_success": kw.get("expected_success", True),
        "expected_diagnostic_present": kw.get("expected_diagnostic_present", False),
        "expected_line": kw.get("expected_line", 0),
        "expected_column": kw.get("expected_column", 0),
        "expected_diagnostic_msg_preview": kw.get("expected_diagnostic_msg_preview", ""),
        "expected_cleanup_runs": kw.get("expected_cleanup_runs", False),
        "expected_errdefer_runs": kw.get("expected_errdefer_runs", False),
        "expected_defer_runs": kw.get("expected_defer_runs", True),
        "expected_catch_runs": kw.get("expected_catch_runs", False),
        "expected_optional_diagnostic": kw.get("expected_optional_diagnostic", False),
        "expected_json_context": kw.get("expected_json_context", False),
        "expected_zon_context": kw.get("expected_zon_context", False),
        "expected_compile_flag_context": kw.get("expected_compile_flag_context", False),
        "operation_label": kw.get("operation_label", "synthetic_parse_case"),
        "zig_feature": kw.get("zig_feature", "error_union"),
        "context_label": kw.get("context_label", "error_union_policy"),
        "expected_zig_status": kw.get("expected_zig_status", "success"),
        "expected_error_union_observation": kw.get("expected_error_union_observation", "success"),
        "expected_diagnostic_observation": kw.get("expected_diagnostic_observation", "none"),
        "expected_errdefer_observation": kw.get("expected_errdefer_observation", "not_run"),
        "expected_testing_observation": kw.get("expected_testing_observation", "pass"),
        "expected_json_zon_observation": kw.get("expected_json_zon_observation", "not_tested"),
        "expected_version_truth": kw.get("expected_version_truth", "local_only"),
        "expected_production_truth": kw.get("expected_production_truth", "not_tested"),
        "fail_reason": kw.get("fail_reason", ""),
        "naive_should_fail": kw.get("naive_should_fail", False),
    }
    cases.append(c)

# 1-10: error union / try / catch / errdefer / defer
add("c01_error_union_success", "error_union_success_marker", fake_record_name="fake_success_case", synthetic_input="synthetic_parse_case_ok", expected_error_label="None", expected_success=True, zig_feature="error_union", context_label="error_union_policy")
add("c02_error_union_failure", "error_union_failure_marker", fake_record_name="fake_failure_case", synthetic_input="synthetic_parse_case_err", expected_error_label="ToyError", expected_success=False, expected_catch_runs=True, zig_feature="error_union", context_label="error_union_policy", expected_zig_status="error", expected_error_union_observation="error")
add("c03_try_propagation", "try_propagation_marker", fake_record_name="fake_try_case", synthetic_input="demo_token_try", expected_error_label="ToyError", expected_success=False, expected_catch_runs=True, operation_label="try_propagation", zig_feature="try", context_label="try_catch_policy", expected_zig_status="error", expected_error_union_observation="error")
add("c04_catch_recovery", "catch_recovery_marker", fake_record_name="fake_catch_case", synthetic_input="demo_token_catch", expected_error_label="ToyError", expected_success=True, expected_catch_runs=True, operation_label="catch_recovery", zig_feature="catch", context_label="try_catch_policy", expected_error_union_observation="recovered")
add("c05_errdefer_runs_on_error", "errdefer_runs_on_error_marker", fake_record_name="fake_errdefer_error", synthetic_input="synthetic_failure_errdefer", expected_error_label="ToyError", expected_success=False, expected_errdefer_runs=True, expected_cleanup_runs=True, expected_defer_runs=True, operation_label="demo_errdefer_case", zig_feature="errdefer", context_label="errdefer_policy", expected_zig_status="error", expected_errdefer_observation="ran")
add("c06_errdefer_not_run_on_success", "errdefer_not_run_on_success_marker", fake_record_name="fake_errdefer_ok", synthetic_input="synthetic_parse_case_ok", expected_error_label="None", expected_success=True, expected_errdefer_runs=False, expected_defer_runs=True, operation_label="demo_errdefer_case", zig_feature="errdefer", context_label="errdefer_policy", expected_errdefer_observation="not_run")
add("c07_defer_runs_success_and_error", "defer_runs_on_success_and_error_marker", fake_record_name="fake_defer_case", synthetic_input="synthetic_parse_case_ok", expected_error_label="None", expected_defer_runs=True, zig_feature="defer", context_label="errdefer_policy", expected_errdefer_observation="not_run")
add("c08_testing_expect_success", "testing_expect_success_marker", fake_record_name="fake_test_case_pass", synthetic_input="fictional_config_ok", expected_success=True, zig_feature="std.testing", context_label="testing_debug_policy", expected_testing_observation="pass")
add("c09_testing_expect_failure_context", "testing_expect_failure_context_marker", fake_record_name="fake_test_case_fail_ctx", synthetic_input="fictional_config_bad", expected_error_label="ToyError", expected_success=False, expected_catch_runs=True, zig_feature="std.testing", context_label="testing_debug_policy", expected_zig_status="error", expected_testing_observation="fail_context_not_run")
add("c10_debug_print_context", "debug_print_context_marker", fake_record_name="fake_debug_print", synthetic_input="sample_context_debug", expected_success=True, zig_feature="std.debug.print", context_label="testing_debug_policy", expected_testing_observation="pass")

# 11-20: diagnostic / out-parameter / no-hidden-alloc
add("c11_breakpoint_context_not_run", "breakpoint_context_not_run", fake_record_name="synthetic_debugger_flag", synthetic_input="toy_diagnostic_breakpoint", expected_success=True, expected_compile_flag_context=True, zig_feature="@breakpoint", context_label="debugger_context_not_run", expected_testing_observation="not_run", expected_production_truth="not_tested")
add("c12_build_option_debugger_flag", "build_option_debugger_flag_marker", fake_record_name="synthetic_debugger_flag", synthetic_input="demo_errdefer_case", expected_success=True, expected_compile_flag_context=True, zig_feature="build_option", context_label="debugger_context_not_run", expected_testing_observation="context_only")
add("c13_no_hidden_allocation_error", "no_hidden_allocation_error_marker", fake_record_name="toy_error_payload_case", synthetic_input="fake_json_value", expected_error_label="ToyError", expected_success=False, expected_diagnostic_present=False, zig_feature="error_set", context_label="no_hidden_allocation_policy", expected_diagnostic_observation="none", expected_zig_status="error")
add("c14_optional_diagnostic_present", "optional_diagnostic_present_marker", fake_record_name="toy_diagnostic", synthetic_input="fake_json_value_bad", expected_error_label="UnexpectedToken", expected_success=False, expected_diagnostic_present=True, expected_optional_diagnostic=True, expected_line=1, expected_column=7, expected_diagnostic_msg_preview="unexpected token", expected_catch_runs=True, operation_label="synthetic_parse_case", zig_feature="diagnostic_out_param", context_label="diagnostic_out_parameter_policy", expected_zig_status="error", expected_diagnostic_observation="present")
add("c15_optional_diagnostic_absent", "optional_diagnostic_absent_marker", fake_record_name="toy_diagnostic", synthetic_input="fake_json_value_bad", expected_error_label="UnexpectedToken", expected_success=False, expected_diagnostic_present=False, expected_optional_diagnostic=False, expected_catch_runs=True, operation_label="synthetic_parse_case", zig_feature="diagnostic_out_param", context_label="diagnostic_out_parameter_policy", expected_zig_status="error", expected_diagnostic_observation="none")
add("c16_diagnostic_out_parameter", "diagnostic_out_parameter_marker", fake_record_name="fake_diagnostic_out", synthetic_input="sample_line_col_input", expected_error_label="ParseError", expected_success=False, expected_diagnostic_present=True, expected_optional_diagnostic=True, expected_line=3, expected_column=12, expected_diagnostic_msg_preview="parse error", operation_label="synthetic_parse_case", zig_feature="diagnostic_out_param", context_label="diagnostic_out_parameter_policy", expected_zig_status="error", expected_diagnostic_observation="present")
add("c17_diagnostic_line_column", "diagnostic_line_column_marker", fake_record_name="sample_line_col", synthetic_input="example_schema_bad", expected_error_label="SchemaMismatch", expected_success=False, expected_diagnostic_present=True, expected_line=2, expected_column=5, expected_diagnostic_msg_preview="schema mismatch", operation_label="synthetic_parse_case", zig_feature="diagnostic_out_param", context_label="diagnostic_out_parameter_policy", expected_zig_status="error", expected_diagnostic_observation="present")
add("c18_diagnostic_expected_actual", "diagnostic_expected_actual_marker", fake_record_name="fake_expected_actual", synthetic_input="fake_json_value_bad", expected_error_label="UnexpectedToken", expected_success=False, expected_diagnostic_present=True, expected_optional_diagnostic=True, expected_diagnostic_msg_preview="expected:", operation_label="synthetic_parse_case", zig_feature="diagnostic_out_param", context_label="diagnostic_out_parameter_policy", expected_zig_status="error", expected_diagnostic_observation="present")
add("c19_diagnostic_capacity_limit", "diagnostic_capacity_limit_marker", fake_record_name="toy_diagnostic", synthetic_input="synthetic_failure", expected_error_label="ToyError", expected_success=False, expected_diagnostic_present=True, expected_diagnostic_msg_preview="truncated", operation_label="synthetic_parse_case", zig_feature="diagnostic_out_param", context_label="no_hidden_allocation_policy", expected_zig_status="error", expected_diagnostic_observation="present")
add("c20_diagnostic_overflow_truncation", "diagnostic_overflow_truncation_marker", fake_record_name="toy_diagnostic", synthetic_input="synthetic_failure_long", expected_error_label="ToyError", expected_success=False, expected_diagnostic_present=True, expected_diagnostic_msg_preview="truncated", operation_label="synthetic_parse_case", zig_feature="diagnostic_out_param", context_label="no_hidden_allocation_policy", expected_zig_status="error", expected_diagnostic_observation="present")

# 21-30: json / zon diagnostics
add("c21_json_unexpected_token_context", "json_unexpected_token_context_marker", fake_record_name="fake_json_value", synthetic_input='fake_json_value_bad_token', expected_error_label="UnexpectedToken", expected_success=False, expected_diagnostic_present=True, expected_json_context=True, operation_label="synthetic_parse_case", zig_feature="std.json", context_label="json_diagnostics_context", expected_zig_status="error", expected_json_zon_observation="context_marker")
add("c22_json_scanner_diagnostics_context", "json_scanner_diagnostics_context_marker", fake_record_name="fake_json_value", synthetic_input='fake_json_scanner_input', expected_error_label="UnexpectedToken", expected_success=False, expected_diagnostic_present=True, expected_json_context=True, operation_label="synthetic_parse_case", zig_feature="std.json", context_label="json_diagnostics_context", expected_zig_status="error", expected_json_zon_observation="context_marker")
add("c23_json_schema_mismatch_context", "json_schema_mismatch_context_marker", fake_record_name="example_schema", synthetic_input='example_schema_mismatch', expected_error_label="SchemaMismatch", expected_success=False, expected_diagnostic_present=True, expected_json_context=True, operation_label="synthetic_parse_case", zig_feature="std.json", context_label="json_diagnostics_context", expected_zig_status="error", expected_json_zon_observation="context_marker")
add("c24_zon_diagnostics_context", "zon_diagnostics_context_marker", fake_record_name="demo_zon_value", synthetic_input='demo_zon_value_bad', expected_error_label="ZonParseError", expected_success=False, expected_diagnostic_present=True, expected_zon_context=True, operation_label="synthetic_parse_case", zig_feature="std.zon", context_label="zon_diagnostics_context", expected_zig_status="error", expected_json_zon_observation="context_marker")
add("c25_zon_parse_context", "zon_parse_context_marker", fake_record_name="demo_zon_value", synthetic_input='demo_zon_value_bad', expected_error_label="ZonParseError", expected_success=False, expected_diagnostic_present=True, expected_zon_context=True, operation_label="synthetic_parse_case", zig_feature="std.zon", context_label="zon_diagnostics_context", expected_zig_status="error", expected_json_zon_observation="context_marker")
add("c26_std_json_not_full_benchmark", "std_json_not_full_benchmark_marker", fake_record_name="fake_json_value", synthetic_input='fake_json_value', expected_success=True, expected_json_context=True, zig_feature="std.json", context_label="production_diagnostics_not_tested", expected_json_zon_observation="context_marker", expected_production_truth="not_tested")
add("c27_std_zon_not_full_benchmark", "std_zon_not_full_benchmark_marker", fake_record_name="demo_zon_value", synthetic_input='demo_zon_value', expected_success=True, expected_zon_context=True, zig_feature="std.zon", context_label="production_diagnostics_not_tested", expected_json_zon_observation="context_marker", expected_production_truth="not_tested")
add("c28_richer_union_return_context", "richer_union_return_context_marker", fake_record_name="toy_error_payload_case", synthetic_input='synthetic_parse_case', expected_error_label="ParseError", expected_success=False, expected_diagnostic_present=True, operation_label="synthetic_parse_case", zig_feature="union_return", context_label="richer_union_policy", expected_error_union_observation="union_payload")
add("c29_error_payload_not_builtin", "error_payload_not_builtin_marker", fake_record_name="toy_error_payload_case", synthetic_input='synthetic_failure', expected_error_label="ToyError", expected_success=False, expected_diagnostic_present=False, zig_feature="error_set", context_label="no_hidden_allocation_policy", expected_diagnostic_observation="none", expected_zig_status="error")
add("c30_error_set_narrow", "error_set_narrow_marker", fake_record_name="fake_test_case", synthetic_input='synthetic_parse_case', expected_error_label="ParseError", expected_success=False, zig_feature="error_set", context_label="error_union_policy", expected_zig_status="error", expected_error_union_observation="error")

# 31-40: error sets / caller payload / cleanup
add("c31_error_set_widening_context", "error_set_widening_context_marker", fake_record_name="fake_test_case", synthetic_input='synthetic_parse_case', expected_error_label="ToyError", expected_success=False, zig_feature="error_set", context_label="error_union_policy", expected_zig_status="error", expected_error_union_observation="error")
add("c32_anyerror_context", "anyerror_context_marker", fake_record_name="fake_test_case", synthetic_input='synthetic_failure', expected_error_label="ToyError", expected_success=False, zig_feature="anyerror", context_label="error_union_policy", expected_zig_status="error", expected_error_union_observation="error")
add("c33_error_name_string_context", "error_name_string_context_marker", fake_record_name="fake_test_case", synthetic_input='synthetic_failure', expected_error_label="ToyError", expected_success=False, zig_feature="error_set", context_label="error_union_policy", expected_error_union_observation="error")
add("c34_stack_trace_context_not_tested", "stack_trace_context_not_tested", fake_record_name="fake_test_case", synthetic_input='synthetic_failure', expected_error_label="ToyError", expected_success=False, zig_feature="std.debug", context_label="debugger_context_not_run", expected_testing_observation="not_tested", expected_production_truth="not_tested")
add("c35_debugger_session_not_tested", "debugger_session_not_tested", fake_record_name="synthetic_debugger_flag", synthetic_input='toy_diagnostic', expected_success=True, expected_compile_flag_context=True, zig_feature="@breakpoint", context_label="debugger_context_not_run", expected_testing_observation="not_tested", expected_production_truth="not_tested")
add("c36_c_out_parameter_comparison", "c_out_parameter_comparison_marker", fake_record_name="fake_diagnostic_out", synthetic_input='sample_line_col_input', expected_error_label="ParseError", expected_success=False, expected_diagnostic_present=True, expected_optional_diagnostic=True, zig_feature="diagnostic_out_param", context_label="comparison_context", expected_zig_status="error", expected_diagnostic_observation="present")
add("c37_rust_result_anyhow_context_not_tested", "rust_result_anyhow_context_not_tested", fake_record_name="toy_error_payload_case", synthetic_input='synthetic_failure', expected_error_label="ToyError", expected_success=False, zig_feature="error_set", context_label="comparison_context", expected_production_truth="not_tested", expected_zig_status="error")
add("c38_odin_error_payload_context_not_tested", "odin_error_payload_context_not_tested", fake_record_name="toy_error_payload_case", synthetic_input='synthetic_failure', expected_error_label="ToyError", expected_success=False, zig_feature="error_set", context_label="comparison_context", expected_production_truth="not_tested", expected_zig_status="error")
add("c39_culture_and_coding_standards_context", "culture_and_coding_standards_context_marker", fake_record_name="fake_test_case", synthetic_input='fictional_config', expected_success=True, zig_feature="error_union", context_label="comparison_context")
add("c40_caller_requested_payload", "caller_requested_payload_marker", fake_record_name="toy_diagnostic", synthetic_input='fake_json_value_bad', expected_error_label="UnexpectedToken", expected_success=False, expected_diagnostic_present=True, expected_optional_diagnostic=True, expected_catch_runs=True, zig_feature="diagnostic_out_param", context_label="diagnostic_out_parameter_policy", expected_zig_status="error", expected_diagnostic_observation="present")

# 41-50: cleanup / safety / version / naive
add("c41_caller_ignored_payload", "caller_ignored_payload_marker", fake_record_name="toy_diagnostic", synthetic_input='fake_json_value_bad', expected_error_label="UnexpectedToken", expected_success=False, expected_diagnostic_present=False, expected_optional_diagnostic=False, expected_catch_runs=True, zig_feature="diagnostic_out_param", context_label="diagnostic_out_parameter_policy", expected_zig_status="error", expected_diagnostic_observation="none")
add("c42_cleanup_on_error", "cleanup_on_error_marker", fake_record_name="fake_errdefer_error", synthetic_input='synthetic_failure_errdefer', expected_error_label="ToyError", expected_success=False, expected_cleanup_runs=True, expected_errdefer_runs=True, expected_defer_runs=True, zig_feature="errdefer", context_label="errdefer_policy", expected_zig_status="error", expected_errdefer_observation="ran")
add("c43_cleanup_private_inner_public_outer_context", "cleanup_private_inner_public_outer_context_marker", fake_record_name="fake_errdefer_error", synthetic_input='synthetic_failure_errdefer', expected_error_label="ToyError", expected_success=False, expected_cleanup_runs=True, expected_errdefer_runs=True, zig_feature="errdefer", context_label="errdefer_policy", expected_zig_status="error", expected_errdefer_observation="ran")
add("c44_no_real_file_input", "no_real_file_input_marker", fake_record_name="fake_test_case", synthetic_input='synthetic_parse_case', expected_success=True, zig_feature="error_union", context_label="safety_scope")
add("c45_no_real_network_input", "no_real_network_input_marker", fake_record_name="fake_test_case", synthetic_input='synthetic_parse_case', expected_success=True, zig_feature="error_union", context_label="safety_scope")
add("c46_no_secret_logging", "no_secret_logging_marker", fake_record_name="fake_test_case", synthetic_input='synthetic_parse_case', expected_success=True, zig_feature="std.debug.print", context_label="safety_scope")
add("c47_production_diagnostics_not_tested", "production_diagnostics_not_tested", fake_record_name="fake_test_case", synthetic_input='synthetic_parse_case', expected_success=True, zig_feature="error_set", context_label="production_diagnostics_not_tested", expected_production_truth="not_tested")
add("c48_version_compatibility", "version_compatibility_marker", fake_record_name="fake_test_case", synthetic_input='synthetic_parse_case', expected_success=True, zig_feature="error_union", context_label="version_compatibility", expected_version_truth="local_only")
add("c49_naive_error_policy_expected_fail", "naive_error_policy_expected_fail", fake_record_name="toy_error_payload_case", synthetic_input='synthetic_failure', expected_error_label="ToyError", expected_success=False, expected_diagnostic_present=False, zig_feature="error_set", context_label="naive_error_policy", expected_error_union_observation="error", expected_diagnostic_observation="none", naive_should_fail=True, fail_reason="naive assumes error payloads always exist, hidden allocation, ignores optional diagnostics, logs secrets")
add("c50_external_language_truth_not_tested", "external_language_truth_not_tested", fake_record_name="toy_error_payload_case", synthetic_input='synthetic_failure', expected_error_label="ToyError", expected_success=False, zig_feature="error_set", context_label="comparison_context", expected_production_truth="not_tested", expected_zig_status="error")

with open("cases.json","w") as f:
    json.dump(cases, f, indent=2)
print(f"Wrote {len(cases)} cases to cases.json")
